# Pre-commit 훅 설정 파일
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        description: "Trim trailing whitespace"
      - id: end-of-file-fixer
        description: "Fix end of files"
      - id: check-yaml
        description: "Check YAML file syntax"
      - id: check-json
        description: "Check JSON file syntax"
      - id: check-merge-conflict
        description: "Check for merge conflicts"
      - id: debug-statements
        description: "Check for debugger imports and py37+ breakpoint() calls"

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        description: "Format Python code with Black"
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        description: "Sort imports with isort"
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        description: "Lint Python code with flake8"
        args: ["--max-line-length=88", "--extend-ignore=E203,W503"]
