services:
  backend:
    image: mcpo-backend:py312-ubuntu22.04
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/backend
    volumes:
      - ./:/app/backend
    stdin_open: true
    tty: true
    command: ["bash"]


