global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Analysis LLM MCP Server
  - job_name: 'analysis-llm-mcp'
    static_configs:
      - targets: ['analysis-llm-mcp:8000']
    scrape_interval: 5s
    metrics_path: '/metrics'

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 10s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 10s

  # Node Exporter (시스템 메트릭스)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Docker 컨테이너 메트릭스
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9323']
    scrape_interval: 15s

# Alertmanager 설정 (선택사항)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# 규칙 파일 로드 (선택사항)
# rule_files:
#   - "alert_rules.yml"









