# 워크플로우의 이름
name: Publish and Cleanup Docker Hub Images

# 워크플로우 실행 조건: 새 릴리즈가 발행될 때 또는 수동 실행
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: false
        default: 'latest'
        type: string

jobs:
  build-push-cleanup:
    # 실행 환경 지정
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. 백엔드 Docker 이미지 빌드 및 푸시
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./kpi_dashboard/backend
          file: ./kpi_dashboard/backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/kpi-backend:${{ github.event.inputs.tag || github.ref_name || 'latest' }}
            ${{ secrets.DOCKERHUB_USERNAME }}/kpi-backend:latest

      # 4. 프론트엔드 Docker 이미지 빌드 및 푸시
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./kpi_dashboard/frontend
          file: ./kpi_dashboard/frontend/Dockerfile
          target: runtime
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/kpi-frontend:${{ github.event.inputs.tag || github.ref_name || 'latest' }}
            ${{ secrets.DOCKERHUB_USERNAME }}/kpi-frontend:latest

